import React from 'react';
import {
  // Common
  Check,
  X,
  Plus,
  Minus,
  Star,
  Heart,
  Bell,
  Mail,
  User,
  Users,
  UserPlus,
  Settings,
  Home,
  Search,
  Menu,

  // Arrows & Navigation
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  ExternalLink,

  // Actions
  Download,
  Upload,
  Edit,
  Trash,
  Copy,
  Share,
  Save,
  Send,
  RefreshCw,
  RotateCcw,
  Link,
  Bookmark,
  Flag,
  Tag,
  Filter,
  SlidersHorizontal,

  // Status
  AlertCircle,
  Info,
  HelpCircle,
  CheckCircle,
  XCircle,

  // Security
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Key,
  Shield,
  Fingerprint,

  // Media
  Play,
  Pause,
  SkipForward,
  SkipBack,
  Volume2,
  VolumeX,
  Maximize,
  Minimize,
  Fullscreen,
  Camera,
  Image,
  Video,
  VideoOff,
  Music,
  Mic,
  MicOff,
  Headphones,

  // UI
  MoreHorizontal,
  MoreVertical,
  Grid,
  List,
  LayoutGrid,
  Layers,
  Layout,
  PanelLeft,
  PanelRight,
  Sidebar,
  Columns,
  Rows,
  Box,

  // Commerce
  ShoppingCart,
  CreditCard,
  DollarSign,
  Percent,
  Truck,
  Package,
  Gift,
  Award,

  // Communication
  MessageCircle,
  Inbox,
  Archive,
  Phone,
  AtSign,

  // Time & Date
  Calendar,
  Clock,

  // Location
  MapPin,
  Globe,
  Compass,
  Map,
  Navigation,

  // Weather
  Sun,
  Moon,
  Thermometer,
  Umbrella,
  Wind,
  Droplet,
  Flame,

  // Nature
  Leaf,
  Mountain,

  // Files & Folders
  Folder,
  File,
  FileText,
  Clipboard,

  // Tech
  Wifi,
  WifiOff,
  Bluetooth,
  Battery,
  Power,
  Cpu,
  Monitor,
  Smartphone,
  Tablet,
  Watch,
  Tv,
  Speaker,
  Printer,
  HardDrive,
  Database,
  Server,
  Cloud,

  // Development
  Code,
  Terminal,
  GitBranch,
  Hash,

  // Social
  Github,
  Linkedin,
  Twitter,
  Facebook,
  Instagram,
  Youtube,
  Twitch,
  Slack,
  Chrome,
  Figma,

  // Misc
  Zap,
  Target,
  Crosshair,
  ThumbsUp,
  ThumbsDown,
  LogIn,
  LogOut,
  Loader2,
  PenTool,
  Brush,
  Palette,
} from 'lucide-react';

/**
 * Creates an icon map for a given size
 */
const createIconMap = (size: number) => ({
  none: null,
  // Common
  Check: <Check size={size} />,
  X: <X size={size} />,
  Plus: <Plus size={size} />,
  Minus: <Minus size={size} />,
  Star: <Star size={size} />,
  Heart: <Heart size={size} />,
  Bell: <Bell size={size} />,
  Mail: <Mail size={size} />,
  User: <User size={size} />,
  Users: <Users size={size} />,
  UserPlus: <UserPlus size={size} />,
  Settings: <Settings size={size} />,
  Home: <Home size={size} />,
  Search: <Search size={size} />,
  Menu: <Menu size={size} />,

  // Arrows & Navigation
  ArrowRight: <ArrowRight size={size} />,
  ArrowLeft: <ArrowLeft size={size} />,
  ArrowUp: <ArrowUp size={size} />,
  ArrowDown: <ArrowDown size={size} />,
  ChevronRight: <ChevronRight size={size} />,
  ChevronLeft: <ChevronLeft size={size} />,
  ChevronUp: <ChevronUp size={size} />,
  ChevronDown: <ChevronDown size={size} />,
  ExternalLink: <ExternalLink size={size} />,

  // Actions
  Download: <Download size={size} />,
  Upload: <Upload size={size} />,
  Edit: <Edit size={size} />,
  Trash: <Trash size={size} />,
  Copy: <Copy size={size} />,
  Share: <Share size={size} />,
  Save: <Save size={size} />,
  Send: <Send size={size} />,
  RefreshCw: <RefreshCw size={size} />,
  RotateCcw: <RotateCcw size={size} />,
  Link: <Link size={size} />,
  Bookmark: <Bookmark size={size} />,
  Flag: <Flag size={size} />,
  Tag: <Tag size={size} />,
  Filter: <Filter size={size} />,
  SlidersHorizontal: <SlidersHorizontal size={size} />,

  // Status
  AlertCircle: <AlertCircle size={size} />,
  Info: <Info size={size} />,
  HelpCircle: <HelpCircle size={size} />,
  CheckCircle: <CheckCircle size={size} />,
  XCircle: <XCircle size={size} />,

  // Security
  Lock: <Lock size={size} />,
  Unlock: <Unlock size={size} />,
  Eye: <Eye size={size} />,
  EyeOff: <EyeOff size={size} />,
  Key: <Key size={size} />,
  Shield: <Shield size={size} />,
  Fingerprint: <Fingerprint size={size} />,

  // Media
  Play: <Play size={size} />,
  Pause: <Pause size={size} />,
  SkipForward: <SkipForward size={size} />,
  SkipBack: <SkipBack size={size} />,
  Volume2: <Volume2 size={size} />,
  VolumeX: <VolumeX size={size} />,
  Maximize: <Maximize size={size} />,
  Minimize: <Minimize size={size} />,
  Fullscreen: <Fullscreen size={size} />,
  Camera: <Camera size={size} />,
  Image: <Image size={size} />,
  Video: <Video size={size} />,
  VideoOff: <VideoOff size={size} />,
  Music: <Music size={size} />,
  Mic: <Mic size={size} />,
  MicOff: <MicOff size={size} />,
  Headphones: <Headphones size={size} />,

  // UI
  MoreHorizontal: <MoreHorizontal size={size} />,
  MoreVertical: <MoreVertical size={size} />,
  Grid: <Grid size={size} />,
  List: <List size={size} />,
  LayoutGrid: <LayoutGrid size={size} />,
  Layers: <Layers size={size} />,
  Layout: <Layout size={size} />,
  PanelLeft: <PanelLeft size={size} />,
  PanelRight: <PanelRight size={size} />,
  Sidebar: <Sidebar size={size} />,
  Columns: <Columns size={size} />,
  Rows: <Rows size={size} />,
  Box: <Box size={size} />,

  // Commerce
  ShoppingCart: <ShoppingCart size={size} />,
  CreditCard: <CreditCard size={size} />,
  DollarSign: <DollarSign size={size} />,
  Percent: <Percent size={size} />,
  Truck: <Truck size={size} />,
  Package: <Package size={size} />,
  Gift: <Gift size={size} />,
  Award: <Award size={size} />,

  // Communication
  MessageCircle: <MessageCircle size={size} />,
  Inbox: <Inbox size={size} />,
  Archive: <Archive size={size} />,
  Phone: <Phone size={size} />,
  AtSign: <AtSign size={size} />,

  // Time & Date
  Calendar: <Calendar size={size} />,
  Clock: <Clock size={size} />,

  // Location
  MapPin: <MapPin size={size} />,
  Globe: <Globe size={size} />,
  Compass: <Compass size={size} />,
  Map: <Map size={size} />,
  Navigation: <Navigation size={size} />,

  // Weather
  Sun: <Sun size={size} />,
  Moon: <Moon size={size} />,
  Thermometer: <Thermometer size={size} />,
  Umbrella: <Umbrella size={size} />,
  Wind: <Wind size={size} />,
  Droplet: <Droplet size={size} />,
  Flame: <Flame size={size} />,

  // Nature
  Leaf: <Leaf size={size} />,
  Mountain: <Mountain size={size} />,

  // Files & Folders
  Folder: <Folder size={size} />,
  File: <File size={size} />,
  FileText: <FileText size={size} />,
  Clipboard: <Clipboard size={size} />,

  // Tech
  Wifi: <Wifi size={size} />,
  WifiOff: <WifiOff size={size} />,
  Bluetooth: <Bluetooth size={size} />,
  Battery: <Battery size={size} />,
  Power: <Power size={size} />,
  Cpu: <Cpu size={size} />,
  Monitor: <Monitor size={size} />,
  Smartphone: <Smartphone size={size} />,
  Tablet: <Tablet size={size} />,
  Watch: <Watch size={size} />,
  Tv: <Tv size={size} />,
  Speaker: <Speaker size={size} />,
  Printer: <Printer size={size} />,
  HardDrive: <HardDrive size={size} />,
  Database: <Database size={size} />,
  Server: <Server size={size} />,
  Cloud: <Cloud size={size} />,

  // Development
  Code: <Code size={size} />,
  Terminal: <Terminal size={size} />,
  GitBranch: <GitBranch size={size} />,
  Hash: <Hash size={size} />,

  // Social
  Github: <Github size={size} />,
  Linkedin: <Linkedin size={size} />,
  Twitter: <Twitter size={size} />,
  Facebook: <Facebook size={size} />,
  Instagram: <Instagram size={size} />,
  Youtube: <Youtube size={size} />,
  Twitch: <Twitch size={size} />,
  Slack: <Slack size={size} />,
  Chrome: <Chrome size={size} />,
  Figma: <Figma size={size} />,

  // Misc
  Zap: <Zap size={size} />,
  Target: <Target size={size} />,
  Crosshair: <Crosshair size={size} />,
  ThumbsUp: <ThumbsUp size={size} />,
  ThumbsDown: <ThumbsDown size={size} />,
  LogIn: <LogIn size={size} />,
  LogOut: <LogOut size={size} />,
  Loader2: <Loader2 size={size} />,
  PenTool: <PenTool size={size} />,
  Brush: <Brush size={size} />,
  Palette: <Palette size={size} />,
});

// Pre-built icon maps for common sizes
export const iconMapXs = createIconMap(12);  // For Badge
export const iconMapSm = createIconMap(16);  // For small components
export const iconMapMd = createIconMap(18);  // For InsetField
export const iconMapLg = createIconMap(20);  // For Button, IconButton
export const iconMapXl = createIconMap(24);  // For FeaturedIcon

// Export the icon names for use in argTypes options
export const iconNames = Object.keys(iconMapLg);

// Helper to create argTypes for icon props
export const createIconArgType = (iconMap: Record<string, React.ReactNode>, description?: string) => ({
  control: 'select' as const,
  options: Object.keys(iconMap),
  mapping: iconMap,
  description: description || 'Select an icon from Lucide icons',
});

// Re-export individual icons for direct use in stories
export {
  Check,
  X,
  Plus,
  Minus,
  Star,
  Heart,
  Bell,
  Mail,
  User,
  Users,
  UserPlus,
  Settings,
  Home,
  Search,
  Menu,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  ExternalLink,
  Download,
  Upload,
  Edit,
  Trash,
  Copy,
  Share,
  Save,
  Send,
  RefreshCw,
  RotateCcw,
  Link,
  Bookmark,
  Flag,
  Tag,
  Filter,
  SlidersHorizontal,
  AlertCircle,
  Info,
  HelpCircle,
  CheckCircle,
  XCircle,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Key,
  Shield,
  Fingerprint,
  Play,
  Pause,
  SkipForward,
  SkipBack,
  Volume2,
  VolumeX,
  Maximize,
  Minimize,
  Fullscreen,
  Camera,
  Image,
  Video,
  VideoOff,
  Music,
  Mic,
  MicOff,
  Headphones,
  MoreHorizontal,
  MoreVertical,
  Grid,
  List,
  LayoutGrid,
  Layers,
  Layout,
  PanelLeft,
  PanelRight,
  Sidebar,
  Columns,
  Rows,
  Box,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Percent,
  Truck,
  Package,
  Gift,
  Award,
  MessageCircle,
  Inbox,
  Archive,
  Phone,
  AtSign,
  Calendar,
  Clock,
  MapPin,
  Globe,
  Compass,
  Map,
  Navigation,
  Sun,
  Moon,
  Thermometer,
  Umbrella,
  Wind,
  Droplet,
  Flame,
  Leaf,
  Mountain,
  Folder,
  File,
  FileText,
  Clipboard,
  Wifi,
  WifiOff,
  Bluetooth,
  Battery,
  Power,
  Cpu,
  Monitor,
  Smartphone,
  Tablet,
  Watch,
  Tv,
  Speaker,
  Printer,
  HardDrive,
  Database,
  Server,
  Cloud,
  Code,
  Terminal,
  GitBranch,
  Hash,
  Github,
  Linkedin,
  Twitter,
  Facebook,
  Instagram,
  Youtube,
  Twitch,
  Slack,
  Chrome,
  Figma,
  Zap,
  Target,
  Crosshair,
  ThumbsUp,
  ThumbsDown,
  LogIn,
  LogOut,
  Loader2,
  PenTool,
  Brush,
  Palette,
};
